/*
 * Curated, high-frequency high-school phrases.
 * This intentionally stays small and reviewable: entries without a reliable
 * fixed phrase leave the phrase row hidden instead of receiving a made-up one.
 */
'use strict';

window.W11_WORD_PHRASES = Object.freeze({
  abandon: 'abandon oneself to 沉溺于；听任',
  ability: 'to the best of one’s ability 竭尽全力',
  absolute: 'absolute zero 绝对零度',
  absorb: 'be absorbed in 专心于；沉浸于',
  accept: 'accept ... as ... 接受；认可……为……',
  access: 'have access to 有权使用；可以接近',
  account: 'account for 说明；占比',
  achieve: 'achieve one’s goal 实现目标',
  act: 'take action 采取行动',
  add: 'add up to 合计达',
  adjust: 'adjust to 适应',
  admit: 'admit doing sth 承认做过某事',
  advance: 'in advance 提前',
  advantage: 'take advantage of 利用',
  affect: 'be affected by 受……影响',
  aim: 'aim at 瞄准；旨在',
  allow: 'allow sb to do sth 允许某人做某事',
  amount: 'a large amount of 大量的',
  apply: 'apply for 申请',
  approve: 'approve of 赞成',
  argue: 'argue with sb about sth 与某人争论某事',
  arrive: 'arrive at 到达；达成',
  attract: 'be attracted to 被……吸引',
  aware: 'be aware of 意识到',
  base: 'be based on 以……为基础',
  benefit: 'benefit from 从……受益',
  belong: 'belong to 属于',
  blame: 'be to blame for 对……负责',
  break: 'break down 出故障；分解',
  bring: 'bring up 抚养；提出',
  build: 'build up 逐步建立；增强',
  calm: 'calm down 冷静下来',
  care: 'take care of 照顾',
  carry: 'carry out 执行',
  catch: 'catch up with 赶上',
  cause: 'cause ... to do sth 使……做某事',
  challenge: 'rise to the challenge 应对挑战',
  charge: 'be in charge of 负责',
  come: 'come across 偶然遇到',
  communicate: 'communicate with 与……交流',
  compare: 'compare ... with ... 把……和……比较',
  concentrate: 'concentrate on 集中于',
  concern: 'be concerned about 关心；担心',
  conduct: 'conduct research 开展研究',
  consider: 'consider doing sth 考虑做某事',
  consist: 'consist of 由……组成',
  contribute: 'contribute to 有助于；促成',
  convince: 'convince sb of sth 使某人相信某事',
  deal: 'deal with 处理；应对',
  decide: 'decide to do sth 决定做某事',
  depend: 'depend on 依靠；取决于',
  devote: 'devote oneself to 致力于',
  differ: 'differ from 与……不同',
  dream: 'dream of 梦想；梦见',
  due: 'be due to 由于；应归功于',
  engage: 'engage in 从事；参加',
  escape: 'escape from 从……逃脱',
  even: 'even if 即使',
  expect: 'expect sb to do sth 期待某人做某事',
  experience: 'have experience in 在……方面有经验',
  face: 'face up to 勇敢面对',
  fail: 'fail to do sth 未能做某事',
  familiar: 'be familiar with 熟悉',
  focus: 'focus on 集中于',
  force: 'force sb to do sth 强迫某人做某事',
  get: 'get along with 与……相处',
  give: 'give up 放弃',
  go: 'go through 经历；仔细检查',
  graduate: 'graduate from 毕业于',
  grow: 'grow up 长大',
  happen: 'happen to do sth 碰巧做某事',
  have: 'have trouble (in) doing sth 做某事有困难',
  help: 'help sb (to) do sth 帮助某人做某事',
  hold: 'hold on 坚持；稍等',
  hope: 'hope to do sth 希望做某事',
  improve: 'improve on 改进',
  include: 'include ... in ... 把……包括在……内',
  increase: 'increase by 增加了；提高了',
  influence: 'have an influence on 对……有影响',
  insist: 'insist on 坚持',
  instead: 'instead of 而不是',
  introduce: 'introduce ... to ... 向……介绍……',
  involve: 'be involved in 参与；涉及',
  keep: 'keep doing sth 继续做某事',
  lead: 'lead to 导致；通向',
  learn: 'learn from 向……学习',
  leave: 'leave ... behind 把……落在后面',
  let: 'let sb do sth 让某人做某事',
  lie: 'lie in 在于',
  likely: 'be likely to do sth 很可能做某事',
  listen: 'listen to 听',
  look: 'look forward to 期待',
  make: 'make a difference 产生影响',
  manage: 'manage to do sth 设法做成某事',
  matter: 'It matters that... ……很重要',
  mean: 'mean to do sth 打算做某事',
  meet: 'meet the needs of 满足……的需要',
  mention: 'mention doing sth 提及做某事',
  mind: 'mind doing sth 介意做某事',
  need: 'need to do sth 需要做某事',
  notice: 'notice sb do/doing sth 注意到某人做/正在做某事',
  object: 'object to 反对',
  occur: 'occur to sb 某人想到',
  offer: 'offer to do sth 主动提出做某事',
  operate: 'operate on 给……动手术',
  oppose: 'be opposed to 反对',
  pay: 'pay attention to 注意',
  perform: 'perform well 表现好',
  permit: 'permit sb to do sth 允许某人做某事',
  persuade: 'persuade sb to do sth 说服某人做某事',
  place: 'take place 发生',
  prefer: 'prefer doing to doing 宁愿……而不愿……',
  prevent: 'prevent ... from doing sth 阻止……做某事',
  protect: 'protect ... from/against ... 保护……免受……',
  prove: 'prove to be 证明是',
  provide: 'provide sb with sth 向某人提供某物',
  put: 'put up with 忍受',
  reach: 'reach an agreement 达成一致',
  realize: 'realize one’s dream 实现梦想',
  realise: 'realise one’s dream 实现梦想',
  recognize: 'be recognized as 被认为是',
  refer: 'refer to 提到；查阅',
  regard: 'regard ... as ... 将……视为……',
  relate: 'relate to 与……有关',
  remain: 'remain to be done 有待完成',
  remind: 'remind sb of sth 使某人想起某事',
  remove: 'remove ... from ... 将……从……移开',
  require: 'require sb to do sth 要求某人做某事',
  result: 'result in 导致',
  risk: 'risk doing sth 冒险做某事',
  run: 'run out of 用完',
  save: 'save ... from ... 把……从……中救出',
  say: 'It is said that... 据说……',
  search: 'search for 寻找',
  see: 'see sb do/doing sth 看见某人做/正在做某事',
  seem: 'seem to do sth 似乎做某事',
  set: 'set up 建立',
  share: 'share ... with ... 与……分享……',
  show: 'show up 出现',
  sit: 'sit down 坐下',
  solve: 'solve the problem 解决问题',
  spend: 'spend time (in) doing sth 花时间做某事',
  stand: 'stand for 代表；象征',
  start: 'start with 以……开始',
  stick: 'stick to 坚持',
  stop: 'stop doing sth 停止做某事',
  struggle: 'struggle with 与……斗争；努力应对',
  succeed: 'succeed in doing sth 成功做成某事',
  suffer: 'suffer from 遭受',
  suggest: 'suggest doing sth 建议做某事',
  supply: 'supply sb with sth 向某人提供某物',
  support: 'support oneself 自立',
  suppose: 'be supposed to 应当；理应',
  take: 'take part in 参加',
  tend: 'tend to do sth 往往会；倾向于',
  thank: 'thank sb for sth 因某事感谢某人',
  think: 'think highly of 高度评价',
  throw: 'throw away 扔掉',
  try: 'try one’s best 尽力',
  turn: 'turn out 结果是；证明是',
  understand: 'come to understand 逐渐理解',
  use: 'make use of 利用',
  value: 'be of great value 很有价值',
  volunteer: 'volunteer to do sth 自愿做某事',
  wait: 'wait for 等待',
  wake: 'wake up 醒来；唤醒',
  want: 'want to do sth 想做某事',
  warn: 'warn sb not to do sth 警告某人不要做某事',
  watch: 'watch sb do/doing sth 观看某人做/正在做某事',
  work: 'work out 算出；解决',
  worry: 'worry about 担心',
  write: 'write down 写下',
  good: 'be good at 擅长',
  responsible: 'be responsible for 对……负责',
  afraid: 'be afraid of 害怕',
  angry: 'be angry with/at 对……生气',
  busy: 'be busy doing sth 忙于做某事',
  different: 'be different from 与……不同',
  fond: 'be fond of 喜欢',
  full: 'be full of 充满',
  interested: 'be interested in 对……感兴趣',
  proud: 'be proud of 为……自豪',
  ready: 'be ready to do sth 准备好做某事',
  similar: 'be similar to 与……相似',
  worth: 'be worth doing 值得做',
  above: 'above all 首先；尤其',
  after: 'look after 照顾',
  away: 'right away 立刻',
  before: 'before long 不久',
  down: 'break down 出故障；分解',
  for: 'for example 例如',
  from: 'learn from 向……学习',
  in: 'in fact 实际上',
  into: 'divide ... into ... 把……分成……',
  of: 'because of 因为；由于',
  on: 'on one’s own 独自',
  out: 'find out 查明',
  over: 'get over 克服；恢复',
  through: 'go through 经历；仔细检查',
  to: 'according to 根据',
  up: 'give up 放弃',
  with: 'deal with 处理；应对',
  without: 'without doubt 无疑',
  adapt: 'adapt to 适应；适合',
  appeal: 'appeal to 吸引；呼吁',
  approach: 'an approach to doing sth 做某事的方法',
  attend: 'attend to 处理；照料',
  avoid: 'avoid doing sth 避免做某事',
  compete: 'compete with/against 与……竞争',
  contain: 'be contained in 包含在……中',
  describe: 'describe ... as ... 把……描述为……',
  determine: 'be determined to do sth 下定决心做某事',
  develop: 'develop into 发展成',
  discover: 'make a discovery 取得发现',
  discuss: 'have a discussion with sb about sth 与某人讨论某事',
  distinguish: 'distinguish A from B 区分 A 和 B',
  divide: 'divide ... into ... 把……分成……',
  earn: 'earn a living 谋生',
  encourage: 'encourage sb to do sth 鼓励某人做某事',
  enjoy: 'enjoy doing sth 喜欢做某事',
  exist: 'come into existence 出现；形成',
  expand: 'expand one’s knowledge 拓展知识面',
  express: 'express oneself 表达自己',
  form: 'form the habit of doing sth 养成做某事的习惯',
  gain: 'gain experience 获得经验',
  guard: 'guard against 防范；提防',
  ignore: 'ignore the fact that 忽视……这一事实',
  inform: 'inform sb of sth 通知某人某事',
  judge: 'judge from/by 根据……判断',
  lack: 'lack of 缺少；缺乏',
  limit: 'be limited to 限于……',
  measure: 'take measures to do sth 采取措施做某事',
  organize: 'organize ... into ... 把……组织成……',
  participate: 'participate in 参加',
  produce: 'be produced in 产自……',
  publish: 'publish a book 出版一本书',
  raise: 'raise awareness of 提高……意识',
  receive: 'receive a letter from 收到……的来信',
  reduce: 'reduce ... by ... 将……减少……',
  reflect: 'reflect on 思考；反省',
  refuse: 'refuse to do sth 拒绝做某事',
  replace: 'replace A with B 用 B 替换 A',
  represent: 'represent ... as ... 把……描绘为……',
  respond: 'respond to 对……作出反应',
  rise: 'rise to one’s feet 起立',
  select: 'select ... from ... 从……中选择……',
  separate: 'separate A from B 将 A 与 B 分开',
  settle: 'settle down 定居；安定下来',
  spread: 'spread to 传播到；蔓延到',
  survive: 'survive on 靠……存活',
  treat: 'treat ... as ... 把……当作……',
  trust: 'put one’s trust in 信任；依赖',
  vary: 'vary from ... to ... 从……到……不同',
  view: 'view ... as ... 把……看作……',
  waste: 'waste time doing sth 浪费时间做某事',
  weigh: 'weigh up 权衡；仔细考虑',
});
